version: '3.8'

services:
  ecommerce.webui:
    build:
      context: .
      dockerfile: src/ECommerce.WebUI/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
